### ISSUE TITLE
[cloud_functions]: flutter build ipa compilation error on v5.5.0

### ISSUE THREAD

**Issue by kurtmarcink** [firebase/flutterfire#17343]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Cloud Functions

### Which platforms are affected?

iOS

### Description

May be similar to https://github.com/firebase/flutterfire/issues/17248. After upgrading cloud_functions to 5.5.0 to 5.3.4, running flutter build ipa fails with an error:

```
Swift Compiler Error (Xcode): Extra argument 'app' in call
<REDACTED>/.pub-cache/hosted/pub.dev/cloud_functions-5.5.0/ios/cloud_functions/Sources/cloud_functions/Fir
ebaseFunctionsPlugin.swift:109:45


Swift Compiler Error (Xcode): Extra argument 'app' in call
<REDACTED>/.pub-cache/hosted/pub.dev/cloud_functions-5.5.0/ios/cloud_functions/Sources/cloud_functions/Fir
ebaseFunctionsPlugin.swift:155:36


Encountered error while archiving for device.
```

### Reproducing the issue

1. Upgrade cloud_functions to 5.5.0
2. Run `flutter build ipa --release --suppress-analytics --no-pub`

### Firebase Core version

3.13.0

### Flutter Version

3.29.3

### Relevant Log Output

```shell
Archiving <REDACTED>
Automatically signing iOS for device deployment using specified development team in Xcode
project: <REDACTED>
Running Xcode build...                                                  
Xcode archive done.                                         109.3s
Failed to build iOS app
Swift Compiler Error (Xcode): Extra argument 'app' in call
<REDACTED>/.pub-cache/hosted/pub.dev/cloud_functions-5.5.0/ios/cloud_functions/Sources/cloud_functions/Fir
ebaseFunctionsPlugin.swift:109:45


Swift Compiler Error (Xcode): Extra argument 'app' in call
<REDACTED>/.pub-cache/hosted/pub.dev/cloud_functions-5.5.0/ios/cloud_functions/Sources/cloud_functions/Fir
ebaseFunctionsPlugin.swift:155:36


Encountered error while archiving for device.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.7.2
Flutter SDK 3.29.3

dependencies:
- algorithmic 0.0.11
- android_id 0.4.0 [flutter]
- another_flushbar 1.12.30 [flutter]
- app_settings 6.1.1 [flutter plugin_platform_interface]
- async 2.12.0 [collection meta]
- auto_size_text_plus 3.0.2 [flutter]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- carousel_slider 5.0.0 [flutter]
- cloud_firestore 5.6.7 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 5.5.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.19.1
- connectivity_plus 6.1.4 [flutter flutter_web_plugins connectivity_plus_platform_interface web meta nm collection]
- country_code_picker 3.3.0 [flutter collection diacritic]
- crypto 3.0.6 [typed_data]
- cupertino_icons 1.0.8
- custom_refresh_indicator 4.0.1 [flutter meta]
- device_info_plus 11.4.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta web win32 win32_registry]                                                                                    
- dlibphonenumber 1.1.37 [protobuf meta fixnum]
- dotted_border 2.1.0 [flutter path_drawing]
- dotted_line 3.2.3 [flutter]
- email_validator 3.0.0
- fast_immutable_collections 11.0.4 [collection meta]
- firebase_analytics 11.4.5 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]                                                                     
- firebase_app_check 0.3.2+5 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]                                                                    
- firebase_auth 5.5.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]                                                                                
- firebase_core 3.13.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.3.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]                                                                             
- firebase_dynamic_links 6.1.5 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]                                                      
- firebase_messaging 15.2.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]                                                                
- firebase_performance 0.10.1+5 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]                                                             
- firebase_remote_config 5.4.3 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]                                                          
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_contacts 1.1.9+2 [flutter]
- flutter_form_builder 10.0.1 [flutter intl]
- flutter_hooks 0.21.2 [flutter]
- flutter_riverpod 2.6.1 [collection flutter meta riverpod state_notifier]
- flutter_timezone 4.1.0 [flutter flutter_web_plugins]
- fluttertoast 8.2.12 [flutter flutter_web_plugins web]
- font_awesome_flutter 10.8.0 [flutter]
- form_builder_validators 11.1.2 [flutter flutter_localizations intl]
- freezed_annotation 3.0.0 [collection json_annotation meta]
- geodesy 0.10.2 [latlong2]
- geojson_vi 2.2.5
- geolocator 14.0.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]                                                                                     
- go_router 15.1.1 [collection flutter flutter_web_plugins logging meta]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- google_maps_cluster_manager 3.1.0 [flutter google_maps_flutter_platform_interface]
- google_maps_flutter 2.12.1 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]                                                             
- google_maps_flutter_platform_interface 2.11.1 [collection flutter plugin_platform_interface stream_transform]                                                                                                       
- google_maps_flutter_web 0.5.12 [collection flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform web]                                                       
- google_sign_in 6.3.0 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]                                                                                       
- google_static_maps_controller 1.1.0 [flutter]
- hooks_riverpod 2.6.1 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- intl 0.19.0 [clock meta path]
- json_annotation 4.9.0 [meta]
- latlong2 0.9.1 [intl]
- linear_progress_bar 1.2.0 [flutter]
- location 8.0.0 [flutter location_platform_interface location_web]
- logger 2.5.0
- material_symbols_icons 4.2815.0 [flutter args path chalkdart glob]
- mixpanel_flutter 2.4.1 [flutter flutter_web_plugins]
- package_info_plus 8.3.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]                                                                                       
- permission_handler 12.0.0+1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]                             
- phone_form_field 10.0.6 [flutter flutter_localizations intl flutter_country_selector circle_flags phone_numbers_parser]                                                                                             
- phone_numbers_parser 9.0.3 [meta]
- pointer_interceptor 0.10.1+2 [flutter flutter_web_plugins pointer_interceptor_ios pointer_interceptor_platform_interface pointer_interceptor_web]                                                                   
- retry 3.1.2
- rive 0.13.20 [collection flutter flutter_web_plugins http meta plugin_platform_interface rive_common]
- riverpod_annotation 2.6.1 [meta riverpod]
- sentry_flutter 8.14.2 [flutter flutter_web_plugins sentry package_info_plus meta ffi file collection]
- sentry_logging 8.14.2 [logging sentry]
- share_plus 10.1.4 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]      
- shared_preferences 2.5.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]        
- sign_in_button 3.2.0 [flutter font_awesome_flutter]
- sign_in_with_apple 7.0.1 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sliver_tools 0.2.12 [flutter]
- sms_autofill 2.4.1 [pin_input_text_field flutter]
- stack_trace 1.12.1 [path]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]                                      
- visibility_detector 0.4.0+2 [flutter]
- webview_flutter 4.11.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]                                                                                               

dev dependencies:
- build_runner 2.4.15 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web web_socket_channel yaml]                                                  
- custom_lint 0.7.5 [analyzer analyzer_plugin args async ci cli_util collection custom_lint_core freezed_annotation json_annotation meta package_config path pub_semver pubspec_parse rxdart uuid yaml]               
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]                          
- freezed 3.0.6 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- json_serializable 6.9.5 [analyzer async build build_config collection dart_style json_annotation meta path pub_semver pubspec_parse source_gen source_helper]                                                       
- riverpod_generator 2.6.5 [analyzer build build_config collection crypto meta path riverpod_analyzer_utils riverpod_annotation source_gen]                                                                           
- riverpod_lint 2.6.5 [analyzer analyzer_plugin collection custom_lint_builder meta path riverpod riverpod_analyzer_utils source_span yaml]                                                                           
- sentry_dart_plugin 2.4.1 [yaml injector ansicolor system_info2 file http crypto convert process properties]                                                                                                         

transitive dependencies:
- _fe_analyzer_shared 80.0.0 [meta]
- _flutterfire_internals 1.3.54 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 7.3.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]                                                                                    
- analyzer_plugin 0.13.0 [analyzer collection dart_style pub_semver yaml path]
- ansicolor 2.0.3
- args 2.7.0
- boolean_selector 2.1.2 [source_span string_scanner]
- build 2.4.2 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.2 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.4 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]                                                     
- build_resolvers 2.4.4 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]                                                                     
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]                                  
- built_collection 5.1.1
- built_value 8.9.5 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]                                                                                                          
- chalkdart 3.0.4 [args]
- characters 1.4.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- ci 0.1.0
- circle_flags 5.0.0 [flutter flutter_svg]
- cli_util 0.4.2 [meta path]
- clock 1.1.2
- cloud_firestore_platform_interface 6.6.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]                                                                                   
- cloud_firestore_web 4.4.7 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins]                                                        
- cloud_functions_platform_interface 5.7.0 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.11.0 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]                                                                                     
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.1.2 [typed_data]
- cross_file 0.3.4+2 [meta web]
- csslib 1.0.2 [source_span]
- custom_lint_builder 0.7.5 [analyzer analyzer_plugin collection custom_lint custom_lint_core custom_lint_visitor glob hotreloader meta package_config path pubspec_parse rxdart]                                     
- custom_lint_core 0.7.5 [analyzer analyzer_plugin collection custom_lint_visitor glob matcher meta package_config path pubspec_parse source_span uuid yaml]                                                          
- custom_lint_visitor 1.0.0+7.3.0 [analyzer]
- dart_style 3.0.1 [analyzer args collection package_config path pub_semver source_span yaml]
- dbus 0.7.11 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.2 [flutter meta plugin_platform_interface]
- diacritic 0.1.6
- fake_async 1.3.2 [clock collection]
- ffi 2.1.4
- file 7.0.1 [meta path]
- firebase_analytics_platform_interface 4.3.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]                                                                                           
- firebase_analytics_web 0.5.10+11 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]                                                         
- firebase_app_check_platform_interface 0.1.1+5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]                                                                                         
- firebase_app_check_web 0.2.0+9 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins web]                                                       
- firebase_auth_platform_interface 7.6.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]                                                                                     
- firebase_auth_web 5.14.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]                                                                        
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.22.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.8.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]                                                                              
- firebase_dynamic_links_platform_interface 0.2.7+5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]                                                                                     
- firebase_messaging_platform_interface 4.6.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]                                                                                           
- firebase_messaging_web 3.10.5 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]                                                   
- firebase_performance_platform_interface 0.1.5+5 [_flutterfire_internals firebase_core flutter plugin_platform_interface]                                                                                            
- firebase_performance_web 0.1.7+11 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins]                                                      
- firebase_remote_config_platform_interface 1.5.3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]                                                                                       
- firebase_remote_config_web 1.8.3 [_flutterfire_internals firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]                                                     
- fixnum 1.1.1
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_country_selector 1.0.14 [flutter flutter_localizations intl diacritic circle_flags phone_numbers_parser]                                                                                                    
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]                                                                                               
- flutter_plugin_android_lifecycle 2.0.27 [flutter]
- flutter_svg 2.0.17 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- geolocator_android 5.0.1+1 [flutter geolocator_platform_interface meta uuid]
- geolocator_apple 2.3.13 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.6 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 4.1.3 [flutter flutter_web_plugins geolocator_platform_interface web]
- geolocator_windows 0.2.5 [flutter geolocator_platform_interface]
- glob 2.1.3 [async collection file path string_scanner]
- globbing 1.0.0 [path]
- google_identity_services_web 0.3.3 [meta web]
- google_maps 8.1.1 [meta web]
- google_maps_flutter_android 2.16.0 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]                                                                               
- google_maps_flutter_ios 2.15.1 [flutter google_maps_flutter_platform_interface stream_transform]
- google_sign_in_android 6.2.0 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.8.1 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.5.0 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4+4 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]                                                                                   
- graphs 2.3.2 [collection]
- hotreloader 4.3.0 [collection logging path stream_transform vm_service watcher]
- html 0.15.5+1 [csslib source_span]
- http 1.3.0 [async http_parser meta web]
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- injector 3.0.0
- io 1.0.5 [meta path string_scanner]
- js 0.7.2
- leak_tracker 10.0.8 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.1.1
- location_platform_interface 6.0.0 [flutter plugin_platform_interface]
- location_web 6.0.0 [flutter flutter_web_plugins http_parser location_platform_interface web]
- logging 1.3.0
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.16.0
- mime 2.0.0
- nm 0.5.0 [dbus]
- octo_image 2.1.0 [flutter]
- package_config 2.2.0 [path]
- package_info_plus_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- path 1.9.1
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.1.0 [meta vector_math]
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]                                                             
- path_provider_android 2.2.16 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- permission_handler_android 13.0.1 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.6 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+5 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.3.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.1.0 [meta collection]
- pin_input_text_field 4.5.2 [flutter]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pointer_interceptor_ios 0.10.1 [flutter plugin_platform_interface pointer_interceptor_platform_interface]
- pointer_interceptor_platform_interface 0.10.0+1 [flutter plugin_platform_interface]
- pointer_interceptor_web 0.10.2+1 [flutter flutter_web_plugins plugin_platform_interface pointer_interceptor_platform_interface web]                                                                                 
- pool 1.5.1 [async stack_trace]
- process 5.0.3 [file path platform]
- properties 2.1.1 [meta]
- protobuf 4.0.0 [collection fixnum meta]
- pub_semver 2.2.0 [collection]
- pubspec_parse 1.5.0 [checked_yaml collection json_annotation pub_semver yaml]
- rive_common 0.4.15 [collection ffi flutter flutter_web_plugins graphs http meta plugin_platform_interface web]                                                                                                      
- riverpod 2.6.1 [collection meta stack_trace state_notifier]
- riverpod_analyzer_utils 0.5.10 [analyzer collection crypto custom_lint_core freezed_annotation meta path source_span]                                                                                               
- rxdart 0.28.0
- sanitize_html 2.1.0 [html meta]
- sentry 8.14.2 [http meta stack_trace uuid collection]
- share_plus_platform_interface 5.0.2 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]                                                                                                     
- shared_preferences_android 2.4.8 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]                                                                       
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.3 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]                                                                   
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 3.0.0 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 2.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 3.0.0 [flutter flutter_web_plugins sign_in_with_apple_platform_interface]
- sky_engine 0.0.0
- source_gen 2.0.0 [analyzer async build dart_style glob path pub_semver source_span yaml]
- source_helper 1.3.5 [analyzer collection source_gen]
- source_span 1.10.1 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.2 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.1 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.5 [synchronized path meta]
- sqflite_darwin 2.4.2 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.4 [async]
- stream_transform 2.1.1
- string_scanner 1.4.1 [source_span]
- synchronized 3.3.1
- system_info2 4.0.0 [globbing path]
- term_glyph 1.2.2
- test_api 0.7.4 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]                                                                                            
- timing 1.0.2 [json_annotation]
- typed_data 1.4.0 [collection]
- url_launcher_android 6.3.15 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.3 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.4.0 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.4 [flutter url_launcher_platform_interface]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- vector_graphics 1.1.18 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.13
- vector_graphics_compiler 1.1.16 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- vm_service 14.3.1
- watcher 1.1.1 [async path]
- web 1.1.1
- web_socket 0.1.6 [web]
- web_socket_channel 3.0.2 [async crypto stream_channel web web_socket]
- webview_flutter_android 4.4.1 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.11.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.20.0 [flutter path webview_flutter_platform_interface]
- win32 5.12.0 [ffi]
- win32_registry 2.1.0 [ffi meta win32]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]

```

</details>

### Additional context and comments

```sh
$ pod --version
1.16.2
```

```sh
$ /usr/bin/xcodebuild -version
Xcode 16.3
Build version 16E140
```

**Comment by SelaseKay** [comment]
Hi @kurtmarcink, thanks for the report. I wasn’t able to reproduce the issue using the following steps:

- Created a new project
- Added `firebase_core` and `cloud_functions`
- Run `flutter build ipa --release --suppress-analytics --no-pub`

I also tested with both CocoaPods and Swift Package Manager. Could you share a minimal reproducible repository that I can clone to investigate further?

**Comment by kurtmarcink** [comment]
@SelaseKay I was able to get a minimal example. You can view it here:
https://github.com/kurtmarcink/cloud_functions_issue_17343_example/tree/master/packages/cloud_functions/cloud_functions/example

The issue occurs when adding the following dependencies to the Podfile:
```
pod 'FirebaseAppCheck'
pod 'GoogleUtilities', :modular_headers => true
```

**Comment by SelaseKay** [comment]
Hi @kurtmarcink, thanks for sharing the example app. I was able to reproduce the issue.
It looks like the problem is related to manually adding dependencies(`FirebaseAppCheck` and `GoogleUtilities`) directly in the `Podfile`. Is there a specific reason you're taking that approach?

If you're looking to use App Check, you can simply add it to your `pubspec.yaml` like this: `firebase_app_check: ^0.3.2+5`.
This will automatically include the required native dependencies, so you won’t need to declare them manually in the Podfile.

**Comment by kurtmarcink** [comment]
Fair enough. Do we understand why specifically this causes this dependency conflict? I imagine other people could see this issue in their apps and are unable to remove the dependency.
