### ISSUE TITLE
[core]: firebase_core_web 3.11.0 fails to compile for web — isA<JSObject>() called on Object-typed catch variable

### ISSUE THREAD

**Issue by TheNoumanDev** [firebase/flutterfire#18611]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Core

### Which platforms are affected?

Web

### Description

#18552 ("fix(core,web): preserve non-JavaScript app errors") added `e.isA<JSObject>()` checks inside two `catch (e) { ... }` blocks in `firebase_core_web.dart` — [`FirebaseCoreWeb.app()`](https://github.com/firebase/flutterfire/blob/e6943a682/packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart#L397) and the secondary-app init path (line 448) — replacing a lint-suppressed `e as JSError`, per review feedback from @Lyokone ([discussion](https://github.com/firebase/flutterfire/pull/18552#discussion_r3747355555))

`catch (e)` gives `e` the static type `Object`. `isA<T extends JSAny?>()` is a `dart:js_interop` extension method. I traced the SDK source directly: on Dart 3.10.x/3.11.x it's declared `on JSAny?`, and only starting **Dart 3.12.0** did it move to a broader `extension NullableObjectUtilExtension on Object?`. `Object` isn't a subtype of `JSAny?`, so on any Dart SDK below 3.12.0 the extension simply doesn't apply, and this fails to compile:

```
The method 'isA' isn't defined for the type 'Object'.
```

This PR's own CI (`web`/`web-wasm` jobs) passed, but ran on Flutter 3.44.9 via the floating `stable` channel (bundles Dart 3.12.2). I've independently reproduced the failure on two other, older environments:

- Flutter 3.38.7 (our CI, exact version pinned) — fails
- Flutter 3.35.4 / Dart 3.9.2 (fresh local repro project on my own machine, unrelated to the above CI) — fails

So this compiles on Dart ≥3.12.0 but not below, across three independent environments. `environment: sdk: ^3.6.0` in `firebase_core_web`'s pubspec doesn't reflect this — it currently lets pub resolve this version onto SDKs where it can't actually compile, which turns into a confusing mid-compile crash rather than a clean dependency-resolution error.

### Reproducing the issue

```
flutter create --platforms web repro && cd repro
flutter pub add firebase_core
flutter build web
```

Resolves `firebase_core_web ^3.11.0` (via `firebase_core: ^4.2.0`+), fails during the dart2js compile step on Flutter <3.44.0. Reproduced this exact way on both Flutter 3.35.4 and 3.38.7.

### Firebase Core version

4.14.0

### Flutter Version

3.38.7 (also independently reproduced on 3.35.4)

### Relevant Log Output

```
From CI (Flutter 3.38.7):

Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../../../../.pub-cache/hosted/pub.dev/firebase_core_web-3.11.0/lib/src/firebase_core_web.dart:397:16:
Error: The method 'isA' isn't defined for the type 'Object'.
 - 'Object' is from 'dart:core'.
        if (!e.isA<JSObject>()) {
               ^^^
../../../../.pub-cache/hosted/pub.dev/firebase_core_web-3.11.0/lib/src/firebase_core_web.dart:448:14:
Error: The method 'isA' isn't defined for the type 'Object'.
 - 'Object' is from 'dart:core'.
      if (!e.isA<JSObject>()) {
             ^^^
Error: Compilation failed.

From an independent local repro (Flutter 3.35.4 / Dart 3.9.2, fresh minimal project):

/Users/nouman/.pub-cache/hosted/pub.dev/firebase_core_web-3.11.0/lib/src/firebase_core_web.dart:397:16:
Error: The method 'isA' isn't defined for the type 'Object'.
 - 'Object' is from 'dart:core'.
        if (!e.isA<JSObject>()) {
               ^^^
/Users/nouman/.pub-cache/hosted/pub.dev/firebase_core_web-3.11.0/lib/src/firebase_core_web.dart:448:14:
Error: The method 'isA' isn't defined for the type 'Object'.
 - 'Object' is from 'dart:core'.
      if (!e.isA<JSObject>()) {
             ^^^
Error: Compilation failed.
```

### Additional context and comments

Introduced in #18552 (commit e6943a682), call sites at `lib/src/firebase_core_web.dart:397` and `:448`.

For now, we've worked around this by pinning `dependency_overrides: firebase_core_web: 3.10.0` until this is resolved, as we can't upgrade the Flutter version right now due to other dependency constraints.

**Comment by SelaseKay** [comment]
Hi @TheNoumanDev, thanks for the report. I'm looking into this.

**Comment by SelaseKay** [comment]
Hi @TheNoumanDev, thanks again for the report. I've created a PR to resolve this.
